### ISSUE TITLE
Adobe Launch - Adjust SDK Extension - Event-Trackers 

### ISSUE THREAD

**Issue by lhocihara-bmg** [adjust/android_adobe_extension#8]
Hi,

I was reading the example app in the documentation (https://github.com/adjust/android_adobe_extension#qs-example-app) and had some doubts on how to add it in our already implemented Adobe Analytics Tracking, using MobileCore. Could you please help me to clarify it?

According to the sample, we have the following code-lines:
![image](https://user-images.githubusercontent.com/131708802/234299040-d2ed0a8a-295f-4b91-824a-d18f1bf80883.png)

Questions:
- Could we use the function "MobileCore.trackState()" instead of "MobileCore.trackAction()"? Does the Adjust SDK interprets this tracking?
- The value "adj.trackEvent", in the first parameter, may not be changed to another value? - like the identifier of the page, recomended in the Adobe Analytics implementation document (https://aep-sdks.gitbook.io/docs/getting-started/initialize-the-sdk#track-app-states-and-screens-for-adobe-analytics)

My questions comes due to the fact that, currently, we only use "MobileCore.trackState()" in our project. And I'm trying to check if we could set the Adjust Event Token as an adictional property in the existing implementation, or we'll need to implement another Adobe Analytics server call, exclusivelly to track Adjust Events.

In advance, if it's not possible to do the setup as described above, I would like to check If we could procedure as it's described in this documentation (https://help.adjust.com/en/article/event-tracking-android-sdk), where, at my point of view, we'll only need to use the Adjust server call, and will not use Adobe Analytics as a bridge between we and Adjust - Avoiding an extra cost due to another server call to Adobe Analytics in every time we want to send an event to Adjust.

I appreciate your help.

**Comment by shashanksu** [comment]
Hi @lhocihara-bmg ,
Thanks for reaching out. In order to track an Adjust Event, one need to use the "MobileCore.trackAction()" function and with passing the action value as "adj.trackEvent".  
In case you want to make a single call, may be try using "MobileCore.trackAction()" in place of "MobileCore.trackState()" in your project. 
As an alternative, try reaching out to the Account Manager to check the possibility of using [S2S](https://help.adjust.com/en/article/server-to-server-events) events.
Hope this helps.

**Comment by shashanksu** [comment]
Hi @lhocihara-bmg,
Closing this, as I see no further queries.  
Hope your issue is resolved.
Thanks
